"""NSFW 域名分流规则（翻译自 ref201-nsfwruleset/NSFW.list）

由 ``tmp_scancheck/_gen_nsfw_domains.py`` 从
``.references/MDCX-Project-Reference/ref201-nsfwruleset/NSFW.list`` 生成，勿手改
（手改会在下次重跑时丢失；要改就改生成器或直接改清单）。

为什么内嵌而不运行时读文件：
    ``.references/`` 是本地参考库，部署到服务器（192.168.10.120）后并不存在，
    运行时读取会静默退化成"没有任何补充规则"。内嵌才能保证两端一致。

规则类型映射（Clash → Xray）：
    DOMAIN-SUFFIX,x  →  ``domain:x``     （命中该域名及其子域名）
    DOMAIN-KEYWORD,x →  ``keyword:x``    （域名子串匹配）

采纳范围（保守优先，宁漏勿滥）：
- 全部 190 条 DOMAIN-SUFFIX：精确到后缀，不会误伤无关流量。
- DOMAIN-KEYWORD 只保留"内容站"类 9 条。
  明确排除的 CDN / 通用类（把 CDN 卷进代理 = 白烧节点流量 + 拖慢 leastPing 测速）：
      akamai / dyncdn / cdnstreamwish / zpod / -plus
      rutrk.org / rutracker / rarbg / sjhs（BT 站，MDCX 不下载）
"""

from __future__ import annotations

#: 精确后缀规则，已带 Xray 前缀，可直接进 routing.rules[].domain
NSFW_SUFFIX_RULES: list[str] = [
    "domain:100606.xyz",
    "domain:18comic.vip",
    "domain:200900.xyz",
    "domain:2dfan.com",
    "domain:3movs.com",
    "domain:4tube.com",
    "domain:69shu.com",
    "domain:7mmtv.sx",
    "domain:acgn.zone",
    "domain:acgnx.se",
    "domain:acgrip.com",
    "domain:alohatube.com",
    "domain:anidb.net",
    "domain:api.themoviedb.org",
    "domain:api.tmdb.org",
    "domain:avcar.vip",
    "domain:bigporn.com",
    "domain:blog.reimu.net",
    "domain:boards.guro.cx",
    "domain:cangku.moe",
    "domain:chinaavg.com",
    "domain:comici.win",
    "domain:cool18.com",
    "domain:cor-games.com",
    "domain:cumlouder.com",
    "domain:dansmovies.com",
    "domain:db.msin.jp",
    "domain:diyibanzhu.me",
    "domain:drtuber.com",
    "domain:emturbovid.com",
    "domain:eyny.com",
    "domain:fantia.jp",
    "domain:fapvidhd.com",
    "domain:fc2ppvdb.com",
    "domain:forhertube.com",
    "domain:freebb.me",
    "domain:fuq.com",
    "domain:fux.com",
    "domain:gmgard.moe",
    "domain:h2porn.com",
    "domain:hacg.me",
    "domain:haho.moe",
    "domain:handjobhub.com",
    "domain:hanime.tv",
    "domain:hanime1.me",
    "domain:hclips.com",
    "domain:hdhive.online",
    "domain:hdhole.com",
    "domain:hentaidude.com",
    "domain:hentaiera.com",
    "domain:hentaitk.net",
    "domain:hentaivideoworld.com",
    "domain:here.xxx",
    "domain:hitomi.la",
    "domain:hotporntubes.com",
    "domain:image.tmdb.org",
    "domain:imcsea.club",
    "domain:img.msin.info",
    "domain:imhentai.xxx",
    "domain:imoutolove.me",
    "domain:its.porn",
    "domain:ixxx.com",
    "domain:javlibrary.com",
    "domain:javxx.com",
    "domain:jellyfin.org",
    "domain:jmcomic-creed.club",
    "domain:jwpcdn.com",
    "domain:jwplayer.com",
    "domain:kanav.info",
    "domain:kemono.su",
    "domain:kimochi.info",
    "domain:kpkuang.org",
    "domain:leijing1.com",
    "domain:linux.do",
    "domain:litvp.com",
    "domain:lobstertube.com",
    "domain:loverslab.com",
    "domain:lvcha.org",
    "domain:maturetube.com",
    "domain:mauobzw.com",
    "domain:megatube.xxx",
    "domain:melonstube.com",
    "domain:metaporn.com",
    "domain:mikanani.me",
    "domain:mirror.jellyfin.org",
    "domain:missav.com",
    "domain:missav.recombee.com",
    "domain:missav123.com",
    "domain:moeli-desu.com",
    "domain:moviemeter.nl",
    "domain:mpdb.tv",
    "domain:mrzyx.xyz",
    "domain:muchohentai.com",
    "domain:myavlive.com",
    "domain:namethatporn.com",
    "domain:njav.tv",
    "domain:nuvid.com",
    "domain:nyaa.si",
    "domain:ofdb.de",
    "domain:ohentai.org",
    "domain:omdbapi.com",
    "domain:onlyhentaistuff.com",
    "domain:orgasm.com",
    "domain:porn.biz",
    "domain:porn.com",
    "domain:porn300.com",
    "domain:porn7.xxx",
    "domain:pornburst.xxx",
    "domain:porndig.com",
    "domain:porndoe.com",
    "domain:porndroids.com",
    "domain:pornerbros.com",
    "domain:pornhd.com",
    "domain:pornheed.com",
    "domain:pornhost.com",
    "domain:pornhub.com",
    "domain:pornid.xxx",
    "domain:pornmaki.com",
    "domain:pornone.com",
    "domain:pornrabbit.com",
    "domain:pornrox.com",
    "domain:porntrex.com",
    "domain:porntube.com",
    "domain:proporn.com",
    "domain:reimu.net",
    "domain:rule34.xxx",
    "domain:rule34video.com",
    "domain:rutracker.cc",
    "domain:rutracker.org",
    "domain:ryuugames.com",
    "domain:sb-cd.com",
    "domain:sehuatang.org",
    "domain:sexinsex.net",
    "domain:sexvid.xxx",
    "domain:shameless.com",
    "domain:share.dmhy.org",
    "domain:skunkgirl.cc",
    "domain:slutload.com",
    "domain:smallcolor.link",
    "domain:snow-plus.net",
    "domain:south-plus.net",
    "domain:spankbang.com",
    "domain:sshs.pw",
    "domain:subtitles.org",
    "domain:sunporno.com",
    "domain:supjav.com",
    "domain:sw-cdnstreamwish.com",
    "domain:tastyblacks.com",
    "domain:thematureporn.net",
    "domain:themoviedb.org",
    "domain:thepiratebay.org",
    "domain:thetvdb.com",
    "domain:thumbzilla.com",
    "domain:tiava.com",
    "domain:tnaflix.com",
    "domain:torrindex.net",
    "domain:trakt.tv",
    "domain:tube8.com",
    "domain:tubev.sex",
    "domain:tv-skyairav.cc",
    "domain:tvmaze.com",
    "domain:upimagez.com",
    "domain:upskirt.tv",
    "domain:v2rayse.com",
    "domain:ver1.sptvp.com",
    "domain:vikacg.com",
    "domain:vintage-erotic.net",
    "domain:vipwank.com",
    "domain:viviporn.tv",
    "domain:white-plus.net",
    "domain:whos.amung.us",
    "domain:wnacg.com",
    "domain:woqukan.com",
    "domain:woyekan.com",
    "domain:xbabe.com",
    "domain:xbookcn.net",
    "domain:xgames.zone",
    "domain:xhamster.com",
    "domain:xiaojiadianmovie.be",
    "domain:xnxx.com",
    "domain:xslist.org",
    "domain:xxxbunker.com",
    "domain:xxxvideo.best",
    "domain:xxxvideos247.com",
    "domain:yadro.ru",
    "domain:youporn.com",
    "domain:zbporn.com",
    "domain:zooqle.com",
    "domain:zpod.net",
    "domain:zyxz.ailoli.us",
]

#: 子串关键词规则（同样已带前缀）；数量刻意很少，避免卷入 CDN
NSFW_KEYWORD_RULES: list[str] = [
    "keyword:fc2",
    "keyword:hentai",
    "keyword:jav",
    "keyword:mikanani",
    "keyword:porn",
    "keyword:themoviedb",
    "keyword:tmdb",
    "keyword:xiaojiadianmovie",
    "keyword:xvideo",
]


def nsfw_rules() -> list[str]:
    """返回可直接写入 Xray routing 的规则串列表。"""
    return [*NSFW_SUFFIX_RULES, *NSFW_KEYWORD_RULES]
