"""
API 路由模块
"""

from fastapi import APIRouter

from app.api.routes import auth, config, files, health, logs, movies, tasks, patch, actors, crawlers, stats, import_, tags, studios, series, nfo, workflows, compare, favorites, fingerprint, mpv, translate, tiers, webdav, network_diag, face_crop, naming, mnamer, site_priority, emby_config, emby_push, strm, nsfw, mosaic, player, proxy_play, plugins, subscriptions, series_subscriptions, subscription_downloader, viewing_reports, users, telegram_bot, view_status, file_organize, cookiecloud, gfriends, unrecognized, cloud_drive2, pan_115, metatube, source_merge, tvbox_config, downloaders, themes, schema, deploy, backup, poster_enhance, movie_graph, recommendations, nfo_scrape, fanart, auto_organize, proxy_xray

api_router = APIRouter()

# 注册路由（auth 放在最前面，不需要认证）
api_router.include_router(auth.router, prefix="/auth", tags=["登录认证"])
api_router.include_router(health.router, prefix="/health", tags=["健康检查"])
api_router.include_router(config.router, prefix="/config", tags=["配置管理"])
api_router.include_router(files.router, prefix="/files", tags=["文件浏览"])
api_router.include_router(logs.router, prefix="/logs", tags=["日志管理"])
api_router.include_router(movies.router, prefix="/movies", tags=["媒体管理"])
api_router.include_router(tasks.router, prefix="/tasks", tags=["任务管理"])
api_router.include_router(patch.router, prefix="/patch", tags=["补刮管理"])
api_router.include_router(actors.router, prefix="/actors", tags=["演员管理"])
api_router.include_router(crawlers.router, prefix="/crawlers", tags=["站点管理"])
api_router.include_router(stats.router, prefix="/stats", tags=["系统统计"])
api_router.include_router(import_.router, prefix="/import", tags=["导入管理"])
api_router.include_router(tags.router, prefix="/tags", tags=["标签管理"])
api_router.include_router(studios.router, prefix="/studios", tags=["厂商管理"])
api_router.include_router(series.router, prefix="/series", tags=["系列管理"])
api_router.include_router(nfo.router, prefix="/nfo", tags=["NFO管理"])
api_router.include_router(workflows.router, prefix="/workflows", tags=["工作流管理"])
api_router.include_router(compare.router, prefix="/compare", tags=["本地在线对比"])
api_router.include_router(favorites.router, prefix="/favorites", tags=["收藏夹管理"])
api_router.include_router(fingerprint.router, prefix="/fingerprint", tags=["视频指纹"])
api_router.include_router(mpv.router, prefix="/mpv", tags=["mpv播放器"])
api_router.include_router(translate.router, prefix="/translate", tags=["翻译"])
api_router.include_router(tiers.router, prefix="/tiers", tags=["分级管理"])
api_router.include_router(webdav.router, prefix="/webdav", tags=["WebDAV"])
api_router.include_router(network_diag.router, prefix="/network-diag", tags=["网络诊断"])
api_router.include_router(face_crop.router, prefix="/face-crop", tags=["人脸裁剪"])
api_router.include_router(naming.router, prefix="/naming", tags=["命名模板"])
api_router.include_router(mnamer.router, prefix="/mnamer", tags=["mnamer智能重命名"])
api_router.include_router(site_priority.router, prefix="/site-priority", tags=["站点优先级"])
api_router.include_router(emby_config.router, prefix="/emby-config", tags=["Emby协议兼容"])
api_router.include_router(emby_push.router, prefix="/emby-push", tags=["Emby元数据推送"])
api_router.include_router(strm.router, prefix="/strm", tags=["STRM文件生成"])
api_router.include_router(nsfw.router, prefix="/nsfw", tags=["NSFW模式"])
api_router.include_router(mosaic.router, prefix="/mosaic", tags=["马赛克识别"])
api_router.include_router(player.router, prefix="/player", tags=["播放器"])
api_router.include_router(proxy_play.router, prefix="/proxy-play", tags=["302反代播放"])
api_router.include_router(plugins.router, prefix="/plugins", tags=["插件系统"])
api_router.include_router(subscriptions.router, prefix="/subscriptions", tags=["演员订阅"])
api_router.include_router(series_subscriptions.router, prefix="/series-subscriptions", tags=["系列订阅"])
api_router.include_router(subscription_downloader.router, prefix="/subscription-downloader", tags=["订阅自动下载"])
api_router.include_router(viewing_reports.router, prefix="/viewing", tags=["观影报告"])
api_router.include_router(users.router, prefix="/users", tags=["用户管理"])
api_router.include_router(telegram_bot.router, prefix="/telegram-bot", tags=["Telegram Bot"])
api_router.include_router(view_status.router, prefix="/view-status", tags=["三态视频标记"])
api_router.include_router(file_organize.router, prefix="/file-organize", tags=["文件整理"])
api_router.include_router(cookiecloud.router, prefix="/cookiecloud", tags=["CookieCloud同步"])
api_router.include_router(gfriends.router, prefix="/gfriends", tags=["Gfriends头像库"])
api_router.include_router(unrecognized.router, prefix="/unrecognized", tags=["未识别文件处理"])
api_router.include_router(cloud_drive2.router, prefix="/cloud-drive2", tags=["CloudDrive2网盘"])
api_router.include_router(pan_115.router, prefix="/pan-115", tags=["115网盘离线下载"])
api_router.include_router(metatube.config_router, prefix="/metatube-config", tags=["Metatube插件配置"])
api_router.include_router(source_merge.router, prefix="/source-merge", tags=["多来源数据精选"])
api_router.include_router(tvbox_config.router, prefix="/tvbox-config", tags=["TVBox/MacCMS开放接口"])
api_router.include_router(downloaders.router, prefix="/downloaders", tags=["下载器统一管理"])
api_router.include_router(themes.router, prefix="/themes", tags=["皮肤主题插件"])
api_router.include_router(schema.router, prefix="/schema", tags=["Schema驱动设置"])
api_router.include_router(deploy.router, prefix="/deploy", tags=["部署档位管理"])
api_router.include_router(backup.router, prefix="/backup", tags=["自动备份管理"])
api_router.include_router(poster_enhance.router, prefix="/poster-enhance", tags=["海报增强"])
api_router.include_router(movie_graph.router, prefix="/movie-graph", tags=["影片图谱"])
api_router.include_router(recommendations.router, prefix="/recommendations", tags=["AI智能推荐"])
api_router.include_router(nfo_scrape.router, prefix="/nfo-scrape", tags=["NFO免改名刮削"])
api_router.include_router(fanart.router, prefix="/fanart", tags=["Fanart背景图"])
api_router.include_router(auto_organize.router, prefix="/auto-organize", tags=["自动整理规则"])
api_router.include_router(proxy_xray.router, prefix="/proxy/xray", tags=["内置Xray代理"])
